stages:
  download:
    cmd: wget https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz -O data/received/imagenette2-160.tgz
    outs:
    - data/received/imagenette2-160.tgz:
        persist: true
  extract:
    cmd: tar -xzvf data/received/imagenette2-160.tgz -C data/raw
    deps:
    - data/received/imagenette2-160.tgz
    outs:
    - data/raw/imagenette2-160:
        persist: true
